packages:
  - 'apps/*'
  - 'packages/*'
minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.11.1'
  - '@turbo/darwin-arm64@2.11.1'
  - '@turbo/linux-64@2.11.1'
  - '@turbo/linux-arm64@2.11.1'
  - '@turbo/windows-64@2.11.1'
  - '@turbo/windows-arm64@2.11.1'
  - turbo@2.11.1
catalog:
  '@aws-sdk/client-s3': 3.1111.0
  '@aws-sdk/lib-storage': 3.1111.0
  '@changesets/changelog-github': 1.0.1
  '@changesets/cli': 3.0.3
  '@changesets/types': 7.0.0
  '@eslint/js': 10.0.1
  '@ngneat/falso': 8.0.2
  '@pnpm/logger': 1001.0.1
  '@pnpm/types': 1000.7.0
  '@pnpm/workspace.pkgs-graph': 1000.0.25
  '@sesamecare-oss/redlock': 1.4.0
  '@shopify/semaphore': 3.1.0
  '@smithy/node-http-handler': 4.11.2
  '@supabase/storage-js': 2.112.3
  '@tus/utils': 0.7.1
  '@types/express': 4.17.21
  '@types/js-yaml': 4.0.9
  '@types/lodash-es': 4.17.12
  '@types/ms': 2.1.0
  '@types/node': 22.13.14
  '@types/react': 19.2.18
  '@types/semver': 7.7.1
  '@vitest/coverage-v8': 3.2.6
  dotenv: 17.2.3
  eslint: 10.9.1
  eslint-config-prettier: 10.1.8
  eslint-plugin-import-x: 4.17.1
  eventemitter2: 6.4.9
  globals: 17.12.0
  ioredis: 5.8.2
  js-yaml: 4.3.2
  lefthook: 2.1.14
  lodash-es: 4.18.1
  lru-cache: 11.2.2
  ms: 2.1.3
  nanoid: 5.1.16
  pino: 9.7.0
  pino-http: 10.5.0
  pino-http-print: 3.1.0
  pino-pretty: 13.1.2
  prettier: 3.9.6
  rate-limiter-flexible: 7.2.0
  react: 19.2.8
  semver: 7.7.3
  tsdown: 0.15.11
  tus-js-client: 4.3.1
  typescript: 5.9.3
  typescript-eslint: 8.70.0
  undici: 7.29.0
  vitest: 3.2.7
  zustand: 5.0.15
allowBuilds:
  esbuild: true
  lefthook: true
  unrs-resolver: true
