packages:
  - 'apps/*'
  - 'packages/*'
minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.11.1'
  - '@turbo/darwin-arm64@2.11.1'
  - '@turbo/linux-64@2.11.1'
  - '@turbo/linux-arm64@2.11.1'
  - '@turbo/windows-64@2.11.1'
  - '@turbo/windows-arm64@2.11.1'
  - turbo@2.11.1
catalog:
  '@aws-sdk/client-s3': 3.1111.0
  '@aws-sdk/lib-storage': 3.1111.0
  '@changesets/changelog-github': 1.0.1
  '@changesets/cli': 3.0.3
  '@eslint/js': 10.0.1
  '@ngneat/falso': 8.0.2
  '@shopify/semaphore': 3.1.0
  '@smithy/node-http-handler': 4.11.2
  '@tus/utils': 0.7.1
  '@types/express': 4.17.21
  '@types/ms': 2.1.0
  '@types/node': 22.13.14
  '@vitest/coverage-v8': 3.2.6
  eslint: 10.9.1
  eslint-config-prettier: 10.1.8
  eslint-plugin-import-x: 4.17.1
  globals: 17.12.0
  lefthook: 2.1.14
  ms: 2.1.3
  prettier: 3.9.6
  tsdown: 0.15.11
  typescript: 5.9.3
  typescript-eslint: 8.70.0
  vitest: 3.2.7
allowBuilds:
  esbuild: true
  lefthook: true
  unrs-resolver: true
