/**
 * Prepositions that stay lower-cased in the middle of a title.
 *
 * {@link handleSpecialWords} matches the lower-cased input word against this list, so entries must be lower-case.
 * Multi-word entries (`in front of`) can never match a single split word; they are kept for completeness of the
 * list.
 */
export const PREPOSITIONS: string[] = [
	'about',
	'above',
	'across',
	'after',
	'against',
	'along',
	'among',
	'around',
	'at',
	'because of',
	'before',
	'behind',
	'below',
	'beneath',
	'beside',
	'besides',
	'between',
	'beyond',
	'but',
	'by',
	'concerning',
	'despite',
	'down',
	'during',
	'except',
	'excepting',
	'for',
	'from',
	'in',
	'in front of',
	'inside',
	'in spite of',
	'instead of',
	'into',
	'like',
	'near',
	'of',
	'off',
	'on',
	'onto',
	'out',
	'outside',
	'over',
	'past',
	'regarding',
	'since',
	'through',
	'throughout',
	'to',
	'toward',
	'under',
	'underneath',
	'until',
	'up',
	'upon',
	'up to',
	'with',
	'within',
	'without',
	'with regard to',
	'with respect to',
];
